title: "Gökhan Namal"
description: "Notes on building, investing, and life."
author: "Gökhan Namal"

# For GitHub Pages (user site)
url: "https://gnamal.com"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

minima:
  skin: classic

# Keep things minimalist
show_excerpts: true

header_pages:
  - about.md
  - now.md
  - projects.md
  - uses.md
  - tags.md
  - search.md

# Optional socials (edit later)
github_username: gokhanamal

# Social
twitter_username: gokhanamal
linkedin_username: gnamal
